apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'flask-app'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['app-service:80']

      - job_name: 'kube-state-metrics'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']

      - job_name: 'kube-state-metrics-health'
        metrics_path: '/healthz'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
