replicaCount: 1

image:
  repository: xskip/cr-api
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3001

config:
  MONGO_URI: "mongodb://mongo-service:27017"
  DB_NAME: "cr-db"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
