apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: xskip/cr-api
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: MONGO_URI
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: DB_NAME
