version: '3'
services:
  mongo:
    image: xskip/cr-mongo:${MONGO_VERSION}
    container_name: mongo
    ports:
      - "27017:27017"

  api:
    image: xskip/cr-api:${API_VERSION}
    container_name: api
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    env_file:
      - .env
 
  app:
    image: xskip/cr-app:${APP_VERSION}
    container_name: app
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - API_URL=${API_URL}
