- name: Create directory for docker-compose
  file:
    path: /opt/{{ project_folder }}
    state: directory
    mode: '0755'

- name: Deploy docker-compose.yaml
  template:
    src: docker-compose.yaml
    dest: /opt/{{ project_folder }}/docker-compose.yaml
  notify:
    - Restart Docker Compose

- name: Deploy .env file
  template:
    src: ".env.j2"
    dest: "/opt/{{ project_folder }}/.env"
    mode: '0644'
  notify:
    - Restart Docker Compose
