apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 27017
