apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
  namespace: default
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      editable: true
