apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3001
  type: {{ .Values.service.type }}
