replicaCount: 1

image:
  repository: xskip/cr-mongo
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017

persistence:
  enabled: true
  storageClass: "manual"
  accessModes:
    - ReadWriteOnce
  size: 10Gi

networkPolicy:
  enabled: true
  allowApiToMongo: true
